/*
* ORGANIZACIÓN DE LENGUAJES Y COMPILADORES 1 SECCIÓN C
* PROYECTO 1 - EXREGAN
* PRIMER SEMESTRE 2023
* NERY JIMÉNEZ - 201700381
*/

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Errors.Errors;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.PrintWriter;

public class interfazExRegan extends javax.swing.JFrame {
    //Variables para el proyecto
    public static String listaItems = "";
    /**
     * Creates new form interfazExRegan
     */
    public interfazExRegan() {
        initComponents();
    }
    
    //Obtener items
    public static String getListaItems(){
        return listaItems;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivo = new javax.swing.JTextArea();
        btnGenerarAutomata = new javax.swing.JButton();
        btnAnalizarEntrada = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        panelImg = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblArchivo = new javax.swing.JLabel();
        lblConsola = new javax.swing.JLabel();
        lblGrafico = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemGuardarComo = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemArboles = new javax.swing.JMenuItem();
        itemSiguientes = new javax.swing.JMenuItem();
        itemTransiciones = new javax.swing.JMenuItem();
        itemAutomatas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArchivo.setColumns(20);
        txtArchivo.setRows(5);
        jScrollPane1.setViewportView(txtArchivo);

        btnGenerarAutomata.setText("Generar Autómata");
        btnGenerarAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarAutomataActionPerformed(evt);
            }
        });

        btnAnalizarEntrada.setText("Analizar Entrada");

        txtConsola.setEditable(false);
        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane2.setViewportView(txtConsola);

        panelImg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelImgLayout = new javax.swing.GroupLayout(panelImg);
        panelImg.setLayout(panelImgLayout);
        panelImgLayout.setHorizontalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        panelImgLayout.setVerticalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnAnterior.setText("Anterior");

        btnSiguiente.setText("Siguiente");

        lblArchivo.setText("Archivo 1");

        lblConsola.setText("Consola");

        lblGrafico.setText("Grafico");

        menuArchivo.setText("Archivo");

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(itemGuardar);

        itemGuardarComo.setText("Guardar Como");
        itemGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarComoActionPerformed(evt);
            }
        });
        menuArchivo.add(itemGuardarComo);

        jMenuBar1.add(menuArchivo);

        menuReportes.setText("Reportes");

        itemArboles.setText("Árboles");
        menuReportes.add(itemArboles);

        itemSiguientes.setText("Tabla de Siguientes");
        menuReportes.add(itemSiguientes);

        itemTransiciones.setText("Tabla de Transiciones");
        menuReportes.add(itemTransiciones);

        itemAutomatas.setText("Autómatas");
        menuReportes.add(itemAutomatas);

        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGenerarAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAnalizarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblConsola)
                            .addComponent(lblArchivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrafico)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArchivo)
                    .addComponent(lblGrafico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarAutomata)
                    .addComponent(btnAnalizarEntrada)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConsola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón Generar autómata
    private void btnGenerarAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarAutomataActionPerformed
        // TODO add your handling code here:
        analizar();
        
    }//GEN-LAST:event_btnGenerarAutomataActionPerformed
    //Menu Abrir archivo
    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".OLC","olc");
        file.setFileFilter(filtro);
        
        int seleccion = file.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = file.getSelectedFile();
            
            try(FileReader fileR = new FileReader(fichero)){
                String cadena = "";
                int valor = fileR.read();
                while(valor != -1){
                    cadena = cadena +(char) valor;
                    valor = fileR.read();
                }
                this.txtArchivo.setText(cadena);
            }catch(IOException el){
            }
        }
    }//GEN-LAST:event_itemAbrirActionPerformed
    //Menu Guardar Como
    private void itemGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarComoActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        int seleccion = file.showSaveDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = file.getSelectedFile();
            
            try(FileWriter fileW = new FileWriter(fichero)){
                fileW.write(this.txtArchivo.getText());
            } catch(IOException el){
            }
        }
    }//GEN-LAST:event_itemGuardarComoActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_itemGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazExRegan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazExRegan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazExRegan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazExRegan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazExRegan().setVisible(true);
            }
        });
    }

    //Metodo para analizar
    public void analizar(){
        listaItems = "";
        ArrayList<Errors> errores = new ArrayList();
        
        try{
            String path = txtArchivo.getText();
            analizador.Lexer Lexico;
            analizador.Parser Sintactico;
            Lexico = new analizador.Lexer(new BufferedReader(new StringReader(path)));
            Sintactico = new analizador.Parser(Lexico);
            Sintactico.parse();
            txtConsola.setText("Item analizado: "+listaItems);
            errores.addAll(Lexico.Errores);
            errores.addAll(Sintactico.getErrores());
            
            generarHtml(errores);
        }catch(Exception e){
        }
    }
    
    //Generar reporte de errores
    public static void generarHtml(ArrayList<Errors> errores) throws IOException {
        FileWriter fichero = null;
        PrintWriter pw = null;
        try{
            String path = "/home/n21/Documentos/USAC/OLC1/LAB/PROYECTOS/PROYECTO1/repo/OLC1-Project1/ERRORES_201700381/Errores.html";
            fichero = new FileWriter(path);
            pw = new PrintWriter(fichero);
            
            //Escribiendo HTML
            pw.println("<!DOCTYPE html>");
            pw.println("<html>");
            pw.println("<head><title>REPORTE DE ERRORES</title>");
            pw.println("<link rel=StyleSheet href=\"stylesheet.css\" type=\"text/css\" ></head>");
            pw.println("<body>");
            pw.println("<h1><span class=\"blue\"></span>EX<span class=\"blue\"></span><span class=\"yellow\">REGAN</pan></h1>");
            pw.println("<h2>Reporte de Errores</h2>");
            pw.println(" <table class=\"container\">");
            pw.println("<thead>");
            pw.println("<tr>");
            pw.println("<th><h1>ERROR</h1></th>");
            pw.println("<th><h1>DESCRIPCION</h1></th>");
            pw.println("<th><h1>FILA</h1></th>");
            pw.println("<th><h1>COLUMNA</h1></th>");
            pw.println("</tr>");
            pw.println("</thead>");
            pw.println("<tbody>");
            
            for (Errors err : errores) {
                pw.println("<tr>");
                 pw.println("<td>" + err.type + "</td>");
                pw.println("<td>" + err.description + "</td>");
                pw.println("<td>" + err.line + "</td>");
                pw.println("<td>" + err.column + "</td>");
                pw.println("</tr>");
            }
            pw.println("</tbody>");
            pw.println("</table>");
            pw.println("</body>");
            pw.println("</html>");
            Desktop.getDesktop().open(new File(path));
        } catch(Exception e){
        } finally{
            if(null != fichero){
                fichero.close();
            }
        }
        try{
            
        }catch(Exception e){
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizarEntrada;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnGenerarAutomata;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemArboles;
    private javax.swing.JMenuItem itemAutomatas;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemGuardarComo;
    private javax.swing.JMenuItem itemSiguientes;
    private javax.swing.JMenuItem itemTransiciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblConsola;
    private javax.swing.JLabel lblGrafico;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JPanel panelImg;
    private javax.swing.JTextArea txtArchivo;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables
}
