
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVDER = 8;
  public static final int MENOS = 11;
  public static final int PUNTO = 21;
  public static final int DOSPUNTOS = 2;
  public static final int CADENA = 16;
  public static final int OR = 22;
  public static final int DECIMAL = 15;
  public static final int PARIZQ = 4;
  public static final int COLOCHO = 20;
  public static final int FLECHA = 19;
  public static final int PARDER = 5;
  public static final int ID = 17;
  public static final int POR = 12;
  public static final int PR_CONJ = 18;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int error = 1;
  public static final int CORIZQ = 6;
  public static final int ENTERO = 14;
  public static final int CORDER = 7;
  public static final int MAS = 10;
  public static final int LLAVIZQ = 9;
  public static final int PTCOMA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNTOS",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAVDER",
  "LLAVIZQ",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ID",
  "PR_CONJ",
  "FLECHA",
  "COLOCHO",
  "PUNTO",
  "OR"
  };
}

